-- MySQL Script generated by MySQL Workbench
-- Fri Feb  3 23:17:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema auto_order_sys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auto_order_sys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auto_order_sys` DEFAULT CHARACTER SET utf8 ;
USE `auto_order_sys` ;

-- -----------------------------------------------------
-- Table `auto_order_sys`.`spec_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`spec_region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `symbol` VARCHAR(45) NOT NULL,
  `spec_region_id` INT NOT NULL,
  PRIMARY KEY (`id`, `name`, `spec_region_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `symbol_UNIQUE` (`symbol` ASC) VISIBLE,
  INDEX `fk_region_spec_region_idx` (`spec_region_id` ASC) VISIBLE,
  CONSTRAINT `fk_region_spec_region`
    FOREIGN KEY (`spec_region_id`)
    REFERENCES `auto_order_sys`.`spec_region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`spec_arial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`spec_arial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`arial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`arial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `spec_arial_id` INT NOT NULL,
  PRIMARY KEY (`id`, `spec_arial_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_arial_spec_arial1_idx` (`spec_arial_id` ASC) VISIBLE,
  CONSTRAINT `fk_arial_spec_arial1`
    FOREIGN KEY (`spec_arial_id`)
    REFERENCES `auto_order_sys`.`spec_arial` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`spec_locality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`spec_locality` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`locality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`locality` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `spec_locality_id` INT NOT NULL,
  PRIMARY KEY (`id`, `spec_locality_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_locality_spec_locality1_idx` (`spec_locality_id` ASC) VISIBLE,
  CONSTRAINT `fk_locality_spec_locality1`
    FOREIGN KEY (`spec_locality_id`)
    REFERENCES `auto_order_sys`.`spec_locality` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`spec_street`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`spec_street` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`street`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`street` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `spec_street_id` INT NOT NULL,
  PRIMARY KEY (`id`, `spec_street_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_street_spec_street1_idx` (`spec_street_id` ASC) VISIBLE,
  CONSTRAINT `fk_street_spec_street1`
    FOREIGN KEY (`spec_street_id`)
    REFERENCES `auto_order_sys`.`spec_street` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`spec_build`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`spec_build` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `short_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`spec_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`spec_room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `short_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`bank` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `BIK` VARCHAR(45) NULL,
  `INN` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`spec_job_title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`spec_job_title` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`executor_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`executor_copy1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `short_name` VARCHAR(45) NULL,
  `INN` VARCHAR(12) NULL,
  `KPP` VARCHAR(12) NULL,
  `director_name` VARCHAR(45) NULL,
  `director_surname` VARCHAR(45) NULL,
  `director_otch` VARCHAR(45) NULL,
  `legal_address_build` VARCHAR(45) NULL,
  `legal_address_room` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `site` VARCHAR(45) NULL,
  `corr_check` VARCHAR(45) NULL,
  `acc_check` VARCHAR(45) NULL,
  `region_id` INT NOT NULL,
  `region_name` VARCHAR(45) NOT NULL,
  `region_spec_region_id` INT NOT NULL,
  `arial_id` INT NOT NULL,
  `arial_spec_arial_id` INT NOT NULL,
  `locality_id` INT NOT NULL,
  `locality_spec_locality_id` INT NOT NULL,
  `area_id` INT NOT NULL,
  `street_id` INT NOT NULL,
  `street_spec_street_id` INT NOT NULL,
  `spec_build_id` INT NOT NULL,
  `spec_room_id` INT NOT NULL,
  `bank_id` INT NOT NULL,
  `spec_job_title_id` INT NOT NULL,
  PRIMARY KEY (`id`, `region_id`, `region_name`, `region_spec_region_id`, `arial_id`, `arial_spec_arial_id`, `locality_id`, `locality_spec_locality_id`, `area_id`, `street_id`, `street_spec_street_id`, `spec_build_id`, `spec_room_id`, `bank_id`, `spec_job_title_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_executor_region1_idx` (`region_id` ASC, `region_name` ASC, `region_spec_region_id` ASC) VISIBLE,
  INDEX `fk_executor_arial1_idx` (`arial_id` ASC, `arial_spec_arial_id` ASC) VISIBLE,
  INDEX `fk_executor_locality1_idx` (`locality_id` ASC, `locality_spec_locality_id` ASC) VISIBLE,
  INDEX `fk_executor_area1_idx` (`area_id` ASC) VISIBLE,
  INDEX `fk_executor_street1_idx` (`street_id` ASC, `street_spec_street_id` ASC) VISIBLE,
  INDEX `fk_executor_spec_build1_idx` (`spec_build_id` ASC) VISIBLE,
  INDEX `fk_executor_spec_room1_idx` (`spec_room_id` ASC) VISIBLE,
  INDEX `fk_executor_bank1_idx` (`bank_id` ASC) VISIBLE,
  INDEX `fk_executor_spec_job_title1_idx` (`spec_job_title_id` ASC) VISIBLE,
  CONSTRAINT `fk_executor_region10`
    FOREIGN KEY (`region_id` , `region_name` , `region_spec_region_id`)
    REFERENCES `auto_order_sys`.`region` (`id` , `name` , `spec_region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_arial10`
    FOREIGN KEY (`arial_id` , `arial_spec_arial_id`)
    REFERENCES `auto_order_sys`.`arial` (`id` , `spec_arial_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_locality10`
    FOREIGN KEY (`locality_id` , `locality_spec_locality_id`)
    REFERENCES `auto_order_sys`.`locality` (`id` , `spec_locality_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_area10`
    FOREIGN KEY (`area_id`)
    REFERENCES `auto_order_sys`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_street10`
    FOREIGN KEY (`street_id` , `street_spec_street_id`)
    REFERENCES `auto_order_sys`.`street` (`id` , `spec_street_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_spec_build10`
    FOREIGN KEY (`spec_build_id`)
    REFERENCES `auto_order_sys`.`spec_build` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_spec_room10`
    FOREIGN KEY (`spec_room_id`)
    REFERENCES `auto_order_sys`.`spec_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_bank10`
    FOREIGN KEY (`bank_id`)
    REFERENCES `auto_order_sys`.`bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_spec_job_title10`
    FOREIGN KEY (`spec_job_title_id`)
    REFERENCES `auto_order_sys`.`spec_job_title` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`executor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`executor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `short_name` VARCHAR(45) NULL,
  `INN` VARCHAR(12) NULL,
  `KPP` VARCHAR(12) NULL,
  `director_name` VARCHAR(45) NULL,
  `director_surname` VARCHAR(45) NULL,
  `director_otch` VARCHAR(45) NULL,
  `legal_address_build` VARCHAR(45) NULL,
  `legal_address_room` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `site` VARCHAR(45) NULL,
  `corr_check` VARCHAR(45) NULL,
  `acc_check` VARCHAR(45) NULL,
  `region_id` INT NOT NULL,
  `region_name` VARCHAR(45) NOT NULL,
  `region_spec_region_id` INT NOT NULL,
  `arial_id` INT NOT NULL,
  `arial_spec_arial_id` INT NOT NULL,
  `locality_id` INT NOT NULL,
  `locality_spec_locality_id` INT NOT NULL,
  `area_id` INT NOT NULL,
  `street_id` INT NOT NULL,
  `street_spec_street_id` INT NOT NULL,
  `spec_build_id` INT NOT NULL,
  `spec_room_id` INT NOT NULL,
  `bank_id` INT NOT NULL,
  `spec_job_title_id` INT NOT NULL,
  PRIMARY KEY (`id`, `region_id`, `region_name`, `region_spec_region_id`, `arial_id`, `arial_spec_arial_id`, `locality_id`, `locality_spec_locality_id`, `area_id`, `street_id`, `street_spec_street_id`, `spec_build_id`, `spec_room_id`, `bank_id`, `spec_job_title_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_executor_region1_idx` (`region_id` ASC, `region_name` ASC, `region_spec_region_id` ASC) VISIBLE,
  INDEX `fk_executor_arial1_idx` (`arial_id` ASC, `arial_spec_arial_id` ASC) VISIBLE,
  INDEX `fk_executor_locality1_idx` (`locality_id` ASC, `locality_spec_locality_id` ASC) VISIBLE,
  INDEX `fk_executor_area1_idx` (`area_id` ASC) VISIBLE,
  INDEX `fk_executor_street1_idx` (`street_id` ASC, `street_spec_street_id` ASC) VISIBLE,
  INDEX `fk_executor_spec_build1_idx` (`spec_build_id` ASC) VISIBLE,
  INDEX `fk_executor_spec_room1_idx` (`spec_room_id` ASC) VISIBLE,
  INDEX `fk_executor_bank1_idx` (`bank_id` ASC) VISIBLE,
  INDEX `fk_executor_spec_job_title1_idx` (`spec_job_title_id` ASC) VISIBLE,
  CONSTRAINT `fk_executor_region1`
    FOREIGN KEY (`region_id` , `region_name` , `region_spec_region_id`)
    REFERENCES `auto_order_sys`.`region` (`id` , `name` , `spec_region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_arial1`
    FOREIGN KEY (`arial_id` , `arial_spec_arial_id`)
    REFERENCES `auto_order_sys`.`arial` (`id` , `spec_arial_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_locality1`
    FOREIGN KEY (`locality_id` , `locality_spec_locality_id`)
    REFERENCES `auto_order_sys`.`locality` (`id` , `spec_locality_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_area1`
    FOREIGN KEY (`area_id`)
    REFERENCES `auto_order_sys`.`area` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_street1`
    FOREIGN KEY (`street_id` , `street_spec_street_id`)
    REFERENCES `auto_order_sys`.`street` (`id` , `spec_street_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_spec_build1`
    FOREIGN KEY (`spec_build_id`)
    REFERENCES `auto_order_sys`.`spec_build` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_spec_room1`
    FOREIGN KEY (`spec_room_id`)
    REFERENCES `auto_order_sys`.`spec_room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_bank1`
    FOREIGN KEY (`bank_id`)
    REFERENCES `auto_order_sys`.`bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_executor_spec_job_title1`
    FOREIGN KEY (`spec_job_title_id`)
    REFERENCES `auto_order_sys`.`spec_job_title` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`spec_contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`spec_contract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`contract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `date_of_conclusion` DATE NOT NULL,
  `date_of_completion` DATE NOT NULL,
  `summ` INT NOT NULL,
  `subject` VARCHAR(100) NOT NULL,
  `short_subject` VARCHAR(10) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `executor_copy1_id` INT NOT NULL,
  `executor_copy1_region_id` INT NOT NULL,
  `executor_copy1_region_name` VARCHAR(45) NOT NULL,
  `executor_copy1_region_spec_region_id` INT NOT NULL,
  `executor_copy1_arial_id` INT NOT NULL,
  `executor_copy1_arial_spec_arial_id` INT NOT NULL,
  `executor_copy1_locality_id` INT NOT NULL,
  `executor_copy1_locality_spec_locality_id` INT NOT NULL,
  `executor_copy1_area_id` INT NOT NULL,
  `executor_copy1_street_id` INT NOT NULL,
  `executor_copy1_street_spec_street_id` INT NOT NULL,
  `executor_copy1_spec_build_id` INT NOT NULL,
  `executor_copy1_spec_room_id` INT NOT NULL,
  `executor_copy1_bank_id` INT NOT NULL,
  `executor_copy1_spec_job_title_id` INT NOT NULL,
  `executor_id` INT NOT NULL,
  `executor_region_id` INT NOT NULL,
  `executor_region_name` VARCHAR(45) NOT NULL,
  `executor_region_spec_region_id` INT NOT NULL,
  `executor_arial_id` INT NOT NULL,
  `executor_arial_spec_arial_id` INT NOT NULL,
  `executor_locality_id` INT NOT NULL,
  `executor_locality_spec_locality_id` INT NOT NULL,
  `executor_area_id` INT NOT NULL,
  `executor_street_id` INT NOT NULL,
  `executor_street_spec_street_id` INT NOT NULL,
  `executor_spec_build_id` INT NOT NULL,
  `executor_spec_room_id` INT NOT NULL,
  `executor_bank_id` INT NOT NULL,
  `executor_spec_job_title_id` INT NOT NULL,
  `spec_contract_id` INT NOT NULL,
  PRIMARY KEY (`id`, `executor_copy1_id`, `executor_copy1_region_id`, `executor_copy1_region_name`, `executor_copy1_region_spec_region_id`, `executor_copy1_arial_id`, `executor_copy1_arial_spec_arial_id`, `executor_copy1_locality_id`, `executor_copy1_locality_spec_locality_id`, `executor_copy1_area_id`, `executor_copy1_street_id`, `executor_copy1_street_spec_street_id`, `executor_copy1_spec_build_id`, `executor_copy1_spec_room_id`, `executor_copy1_bank_id`, `executor_copy1_spec_job_title_id`, `executor_id`, `executor_region_id`, `executor_region_name`, `executor_region_spec_region_id`, `executor_arial_id`, `executor_arial_spec_arial_id`, `executor_locality_id`, `executor_locality_spec_locality_id`, `executor_area_id`, `executor_street_id`, `executor_street_spec_street_id`, `executor_spec_build_id`, `executor_spec_room_id`, `executor_bank_id`, `executor_spec_job_title_id`, `spec_contract_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_contract_executor_copy11_idx` (`executor_copy1_id` ASC, `executor_copy1_region_id` ASC, `executor_copy1_region_name` ASC, `executor_copy1_region_spec_region_id` ASC, `executor_copy1_arial_id` ASC, `executor_copy1_arial_spec_arial_id` ASC, `executor_copy1_locality_id` ASC, `executor_copy1_locality_spec_locality_id` ASC, `executor_copy1_area_id` ASC, `executor_copy1_street_id` ASC, `executor_copy1_street_spec_street_id` ASC, `executor_copy1_spec_build_id` ASC, `executor_copy1_spec_room_id` ASC, `executor_copy1_bank_id` ASC, `executor_copy1_spec_job_title_id` ASC) VISIBLE,
  INDEX `fk_contract_executor1_idx` (`executor_id` ASC, `executor_region_id` ASC, `executor_region_name` ASC, `executor_region_spec_region_id` ASC, `executor_arial_id` ASC, `executor_arial_spec_arial_id` ASC, `executor_locality_id` ASC, `executor_locality_spec_locality_id` ASC, `executor_area_id` ASC, `executor_street_id` ASC, `executor_street_spec_street_id` ASC, `executor_spec_build_id` ASC, `executor_spec_room_id` ASC, `executor_bank_id` ASC, `executor_spec_job_title_id` ASC) VISIBLE,
  INDEX `fk_contract_spec_contract1_idx` (`spec_contract_id` ASC) VISIBLE,
  CONSTRAINT `fk_contract_executor_copy11`
    FOREIGN KEY (`executor_copy1_id` , `executor_copy1_region_id` , `executor_copy1_region_name` , `executor_copy1_region_spec_region_id` , `executor_copy1_arial_id` , `executor_copy1_arial_spec_arial_id` , `executor_copy1_locality_id` , `executor_copy1_locality_spec_locality_id` , `executor_copy1_area_id` , `executor_copy1_street_id` , `executor_copy1_street_spec_street_id` , `executor_copy1_spec_build_id` , `executor_copy1_spec_room_id` , `executor_copy1_bank_id` , `executor_copy1_spec_job_title_id`)
    REFERENCES `auto_order_sys`.`executor_copy1` (`id` , `region_id` , `region_name` , `region_spec_region_id` , `arial_id` , `arial_spec_arial_id` , `locality_id` , `locality_spec_locality_id` , `area_id` , `street_id` , `street_spec_street_id` , `spec_build_id` , `spec_room_id` , `bank_id` , `spec_job_title_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_executor1`
    FOREIGN KEY (`executor_id` , `executor_region_id` , `executor_region_name` , `executor_region_spec_region_id` , `executor_arial_id` , `executor_arial_spec_arial_id` , `executor_locality_id` , `executor_locality_spec_locality_id` , `executor_area_id` , `executor_street_id` , `executor_street_spec_street_id` , `executor_spec_build_id` , `executor_spec_room_id` , `executor_bank_id` , `executor_spec_job_title_id`)
    REFERENCES `auto_order_sys`.`executor` (`id` , `region_id` , `region_name` , `region_spec_region_id` , `arial_id` , `arial_spec_arial_id` , `locality_id` , `locality_spec_locality_id` , `area_id` , `street_id` , `street_spec_street_id` , `spec_build_id` , `spec_room_id` , `bank_id` , `spec_job_title_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_spec_contract1`
    FOREIGN KEY (`spec_contract_id`)
    REFERENCES `auto_order_sys`.`spec_contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`object` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `arial` VARCHAR(45) NULL,
  `locality` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `arial` VARCHAR(45) NULL,
  `area` VARCHAR(45) NULL,
  `build` VARCHAR(45) NULL,
  `room` VARCHAR(45) NULL,
  `period_of_maintence` VARCHAR(45) NULL,
  `contract_id` INT NOT NULL,
  `contract_executor_copy1_id` INT NOT NULL,
  `contract_executor_copy1_region_id` INT NOT NULL,
  `contract_executor_copy1_region_name` VARCHAR(45) NOT NULL,
  `contract_executor_copy1_region_spec_region_id` INT NOT NULL,
  `contract_executor_copy1_arial_id` INT NOT NULL,
  `contract_executor_copy1_arial_spec_arial_id` INT NOT NULL,
  `contract_executor_copy1_locality_id` INT NOT NULL,
  `contract_executor_copy1_locality_spec_locality_id` INT NOT NULL,
  `contract_executor_copy1_area_id` INT NOT NULL,
  `contract_executor_copy1_street_id` INT NOT NULL,
  `contract_executor_copy1_street_spec_street_id` INT NOT NULL,
  `contract_executor_copy1_spec_build_id` INT NOT NULL,
  `contract_executor_copy1_spec_room_id` INT NOT NULL,
  `contract_executor_copy1_bank_id` INT NOT NULL,
  `contract_executor_copy1_spec_job_title_id` INT NOT NULL,
  `contract_executor_id` INT NOT NULL,
  `contract_executor_region_id` INT NOT NULL,
  `contract_executor_region_name` VARCHAR(45) NOT NULL,
  `contract_executor_region_spec_region_id` INT NOT NULL,
  `contract_executor_arial_id` INT NOT NULL,
  `contract_executor_arial_spec_arial_id` INT NOT NULL,
  `contract_executor_locality_id` INT NOT NULL,
  `contract_executor_locality_spec_locality_id` INT NOT NULL,
  `contract_executor_area_id` INT NOT NULL,
  `contract_executor_street_id` INT NOT NULL,
  `contract_executor_street_spec_street_id` INT NOT NULL,
  `contract_executor_spec_build_id` INT NOT NULL,
  `contract_executor_spec_room_id` INT NOT NULL,
  `contract_executor_bank_id` INT NOT NULL,
  `contract_executor_spec_job_title_id` INT NOT NULL,
  `contract_spec_contract_id` INT NOT NULL,
  PRIMARY KEY (`id`, `contract_id`, `contract_executor_copy1_id`, `contract_executor_copy1_region_id`, `contract_executor_copy1_region_name`, `contract_executor_copy1_region_spec_region_id`, `contract_executor_copy1_arial_id`, `contract_executor_copy1_arial_spec_arial_id`, `contract_executor_copy1_locality_id`, `contract_executor_copy1_locality_spec_locality_id`, `contract_executor_copy1_area_id`, `contract_executor_copy1_street_id`, `contract_executor_copy1_street_spec_street_id`, `contract_executor_copy1_spec_build_id`, `contract_executor_copy1_spec_room_id`, `contract_executor_copy1_bank_id`, `contract_executor_copy1_spec_job_title_id`, `contract_executor_id`, `contract_executor_region_id`, `contract_executor_region_name`, `contract_executor_region_spec_region_id`, `contract_executor_arial_id`, `contract_executor_arial_spec_arial_id`, `contract_executor_locality_id`, `contract_executor_locality_spec_locality_id`, `contract_executor_area_id`, `contract_executor_street_id`, `contract_executor_street_spec_street_id`, `contract_executor_spec_build_id`, `contract_executor_spec_room_id`, `contract_executor_bank_id`, `contract_executor_spec_job_title_id`, `contract_spec_contract_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_object_contract1_idx` (`contract_id` ASC, `contract_executor_copy1_id` ASC, `contract_executor_copy1_region_id` ASC, `contract_executor_copy1_region_name` ASC, `contract_executor_copy1_region_spec_region_id` ASC, `contract_executor_copy1_arial_id` ASC, `contract_executor_copy1_arial_spec_arial_id` ASC, `contract_executor_copy1_locality_id` ASC, `contract_executor_copy1_locality_spec_locality_id` ASC, `contract_executor_copy1_area_id` ASC, `contract_executor_copy1_street_id` ASC, `contract_executor_copy1_street_spec_street_id` ASC, `contract_executor_copy1_spec_build_id` ASC, `contract_executor_copy1_spec_room_id` ASC, `contract_executor_copy1_bank_id` ASC, `contract_executor_copy1_spec_job_title_id` ASC, `contract_executor_id` ASC, `contract_executor_region_id` ASC, `contract_executor_region_name` ASC, `contract_executor_region_spec_region_id` ASC, `contract_executor_arial_id` ASC, `contract_executor_arial_spec_arial_id` ASC, `contract_executor_locality_id` ASC, `contract_executor_locality_spec_locality_id` ASC, `contract_executor_area_id` ASC, `contract_executor_street_id` ASC, `contract_executor_street_spec_street_id` ASC, `contract_executor_spec_build_id` ASC, `contract_executor_spec_room_id` ASC, `contract_executor_bank_id` ASC, `contract_executor_spec_job_title_id` ASC, `contract_spec_contract_id` ASC) VISIBLE,
  CONSTRAINT `fk_object_contract1`
    FOREIGN KEY (`contract_id` , `contract_executor_copy1_id` , `contract_executor_copy1_region_id` , `contract_executor_copy1_region_name` , `contract_executor_copy1_region_spec_region_id` , `contract_executor_copy1_arial_id` , `contract_executor_copy1_arial_spec_arial_id` , `contract_executor_copy1_locality_id` , `contract_executor_copy1_locality_spec_locality_id` , `contract_executor_copy1_area_id` , `contract_executor_copy1_street_id` , `contract_executor_copy1_street_spec_street_id` , `contract_executor_copy1_spec_build_id` , `contract_executor_copy1_spec_room_id` , `contract_executor_copy1_bank_id` , `contract_executor_copy1_spec_job_title_id` , `contract_executor_id` , `contract_executor_region_id` , `contract_executor_region_name` , `contract_executor_region_spec_region_id` , `contract_executor_arial_id` , `contract_executor_arial_spec_arial_id` , `contract_executor_locality_id` , `contract_executor_locality_spec_locality_id` , `contract_executor_area_id` , `contract_executor_street_id` , `contract_executor_street_spec_street_id` , `contract_executor_spec_build_id` , `contract_executor_spec_room_id` , `contract_executor_bank_id` , `contract_executor_spec_job_title_id` , `contract_spec_contract_id`)
    REFERENCES `auto_order_sys`.`contract` (`id` , `executor_copy1_id` , `executor_copy1_region_id` , `executor_copy1_region_name` , `executor_copy1_region_spec_region_id` , `executor_copy1_arial_id` , `executor_copy1_arial_spec_arial_id` , `executor_copy1_locality_id` , `executor_copy1_locality_spec_locality_id` , `executor_copy1_area_id` , `executor_copy1_street_id` , `executor_copy1_street_spec_street_id` , `executor_copy1_spec_build_id` , `executor_copy1_spec_room_id` , `executor_copy1_bank_id` , `executor_copy1_spec_job_title_id` , `executor_id` , `executor_region_id` , `executor_region_name` , `executor_region_spec_region_id` , `executor_arial_id` , `executor_arial_spec_arial_id` , `executor_locality_id` , `executor_locality_spec_locality_id` , `executor_area_id` , `executor_street_id` , `executor_street_spec_street_id` , `executor_spec_build_id` , `executor_spec_room_id` , `executor_bank_id` , `executor_spec_job_title_id` , `spec_contract_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`spec_equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`spec_equipment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`regulations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`regulations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `period` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`operation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `scope` VARCHAR(45) NULL,
  `regulations_id` INT NOT NULL,
  PRIMARY KEY (`id`, `regulations_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_operation_regulations1_idx` (`regulations_id` ASC) VISIBLE,
  CONSTRAINT `fk_operation_regulations1`
    FOREIGN KEY (`regulations_id`)
    REFERENCES `auto_order_sys`.`regulations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_order_sys`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_order_sys`.`equipment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `spec_equipment_id` INT NOT NULL,
  `operation_id` INT NOT NULL,
  `object_id` INT NOT NULL,
  `object_contract_id` INT NOT NULL,
  `object_contract_executor_copy1_id` INT NOT NULL,
  `object_contract_executor_copy1_region_id` INT NOT NULL,
  `object_contract_executor_copy1_region_name` VARCHAR(45) NOT NULL,
  `object_contract_executor_copy1_region_spec_region_id` INT NOT NULL,
  `object_contract_executor_copy1_arial_id` INT NOT NULL,
  `object_contract_executor_copy1_arial_spec_arial_id` INT NOT NULL,
  `object_contract_executor_copy1_locality_id` INT NOT NULL,
  `object_contract_executor_copy1_locality_spec_locality_id` INT NOT NULL,
  `object_contract_executor_copy1_area_id` INT NOT NULL,
  `object_contract_executor_copy1_street_id` INT NOT NULL,
  `object_contract_executor_copy1_street_spec_street_id` INT NOT NULL,
  `object_contract_executor_copy1_spec_build_id` INT NOT NULL,
  `object_contract_executor_copy1_spec_room_id` INT NOT NULL,
  `object_contract_executor_copy1_bank_id` INT NOT NULL,
  `object_contract_executor_copy1_spec_job_title_id` INT NOT NULL,
  `object_contract_executor_id` INT NOT NULL,
  `object_contract_executor_region_id` INT NOT NULL,
  `object_contract_executor_region_name` VARCHAR(45) NOT NULL,
  `object_contract_executor_region_spec_region_id` INT NOT NULL,
  `object_contract_executor_arial_id` INT NOT NULL,
  `object_contract_executor_arial_spec_arial_id` INT NOT NULL,
  `object_contract_executor_locality_id` INT NOT NULL,
  `object_contract_executor_locality_spec_locality_id` INT NOT NULL,
  `object_contract_executor_area_id` INT NOT NULL,
  `object_contract_executor_street_id` INT NOT NULL,
  `object_contract_executor_street_spec_street_id` INT NOT NULL,
  `object_contract_executor_spec_build_id` INT NOT NULL,
  `object_contract_executor_spec_room_id` INT NOT NULL,
  `object_contract_executor_bank_id` INT NOT NULL,
  `object_contract_executor_spec_job_title_id` INT NOT NULL,
  `object_contract_spec_contract_id` INT NOT NULL,
  PRIMARY KEY (`id`, `spec_equipment_id`, `operation_id`, `object_id`, `object_contract_id`, `object_contract_executor_copy1_id`, `object_contract_executor_copy1_region_id`, `object_contract_executor_copy1_region_name`, `object_contract_executor_copy1_region_spec_region_id`, `object_contract_executor_copy1_arial_id`, `object_contract_executor_copy1_arial_spec_arial_id`, `object_contract_executor_copy1_locality_id`, `object_contract_executor_copy1_locality_spec_locality_id`, `object_contract_executor_copy1_area_id`, `object_contract_executor_copy1_street_id`, `object_contract_executor_copy1_street_spec_street_id`, `object_contract_executor_copy1_spec_build_id`, `object_contract_executor_copy1_spec_room_id`, `object_contract_executor_copy1_bank_id`, `object_contract_executor_copy1_spec_job_title_id`, `object_contract_executor_id`, `object_contract_executor_region_id`, `object_contract_executor_region_name`, `object_contract_executor_region_spec_region_id`, `object_contract_executor_arial_id`, `object_contract_executor_arial_spec_arial_id`, `object_contract_executor_locality_id`, `object_contract_executor_locality_spec_locality_id`, `object_contract_executor_area_id`, `object_contract_executor_street_id`, `object_contract_executor_street_spec_street_id`, `object_contract_executor_spec_build_id`, `object_contract_executor_spec_room_id`, `object_contract_executor_bank_id`, `object_contract_executor_spec_job_title_id`, `object_contract_spec_contract_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_equipment_spec_equipment1_idx` (`spec_equipment_id` ASC) VISIBLE,
  INDEX `fk_equipment_operation1_idx` (`operation_id` ASC) VISIBLE,
  INDEX `fk_equipment_object1_idx` (`object_id` ASC, `object_contract_id` ASC, `object_contract_executor_copy1_id` ASC, `object_contract_executor_copy1_region_id` ASC, `object_contract_executor_copy1_region_name` ASC, `object_contract_executor_copy1_region_spec_region_id` ASC, `object_contract_executor_copy1_arial_id` ASC, `object_contract_executor_copy1_arial_spec_arial_id` ASC, `object_contract_executor_copy1_locality_id` ASC, `object_contract_executor_copy1_locality_spec_locality_id` ASC, `object_contract_executor_copy1_area_id` ASC, `object_contract_executor_copy1_street_id` ASC, `object_contract_executor_copy1_street_spec_street_id` ASC, `object_contract_executor_copy1_spec_build_id` ASC, `object_contract_executor_copy1_spec_room_id` ASC, `object_contract_executor_copy1_bank_id` ASC, `object_contract_executor_copy1_spec_job_title_id` ASC, `object_contract_executor_id` ASC, `object_contract_executor_region_id` ASC, `object_contract_executor_region_name` ASC, `object_contract_executor_region_spec_region_id` ASC, `object_contract_executor_arial_id` ASC, `object_contract_executor_arial_spec_arial_id` ASC, `object_contract_executor_locality_id` ASC, `object_contract_executor_locality_spec_locality_id` ASC, `object_contract_executor_area_id` ASC, `object_contract_executor_street_id` ASC, `object_contract_executor_street_spec_street_id` ASC, `object_contract_executor_spec_build_id` ASC, `object_contract_executor_spec_room_id` ASC, `object_contract_executor_bank_id` ASC, `object_contract_executor_spec_job_title_id` ASC, `object_contract_spec_contract_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_spec_equipment1`
    FOREIGN KEY (`spec_equipment_id`)
    REFERENCES `auto_order_sys`.`spec_equipment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipment_operation1`
    FOREIGN KEY (`operation_id`)
    REFERENCES `auto_order_sys`.`operation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipment_object1`
    FOREIGN KEY (`object_id` , `object_contract_id` , `object_contract_executor_copy1_id` , `object_contract_executor_copy1_region_id` , `object_contract_executor_copy1_region_name` , `object_contract_executor_copy1_region_spec_region_id` , `object_contract_executor_copy1_arial_id` , `object_contract_executor_copy1_arial_spec_arial_id` , `object_contract_executor_copy1_locality_id` , `object_contract_executor_copy1_locality_spec_locality_id` , `object_contract_executor_copy1_area_id` , `object_contract_executor_copy1_street_id` , `object_contract_executor_copy1_street_spec_street_id` , `object_contract_executor_copy1_spec_build_id` , `object_contract_executor_copy1_spec_room_id` , `object_contract_executor_copy1_bank_id` , `object_contract_executor_copy1_spec_job_title_id` , `object_contract_executor_id` , `object_contract_executor_region_id` , `object_contract_executor_region_name` , `object_contract_executor_region_spec_region_id` , `object_contract_executor_arial_id` , `object_contract_executor_arial_spec_arial_id` , `object_contract_executor_locality_id` , `object_contract_executor_locality_spec_locality_id` , `object_contract_executor_area_id` , `object_contract_executor_street_id` , `object_contract_executor_street_spec_street_id` , `object_contract_executor_spec_build_id` , `object_contract_executor_spec_room_id` , `object_contract_executor_bank_id` , `object_contract_executor_spec_job_title_id` , `object_contract_spec_contract_id`)
    REFERENCES `auto_order_sys`.`object` (`id` , `contract_id` , `contract_executor_copy1_id` , `contract_executor_copy1_region_id` , `contract_executor_copy1_region_name` , `contract_executor_copy1_region_spec_region_id` , `contract_executor_copy1_arial_id` , `contract_executor_copy1_arial_spec_arial_id` , `contract_executor_copy1_locality_id` , `contract_executor_copy1_locality_spec_locality_id` , `contract_executor_copy1_area_id` , `contract_executor_copy1_street_id` , `contract_executor_copy1_street_spec_street_id` , `contract_executor_copy1_spec_build_id` , `contract_executor_copy1_spec_room_id` , `contract_executor_copy1_bank_id` , `contract_executor_copy1_spec_job_title_id` , `contract_executor_id` , `contract_executor_region_id` , `contract_executor_region_name` , `contract_executor_region_spec_region_id` , `contract_executor_arial_id` , `contract_executor_arial_spec_arial_id` , `contract_executor_locality_id` , `contract_executor_locality_spec_locality_id` , `contract_executor_area_id` , `contract_executor_street_id` , `contract_executor_street_spec_street_id` , `contract_executor_spec_build_id` , `contract_executor_spec_room_id` , `contract_executor_bank_id` , `contract_executor_spec_job_title_id` , `contract_spec_contract_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
